import { createContext, ReactNode, useContext, useMemo, useState } from 'react';

export type Language = 'en' | 'vi';

type TranslationKey = string;

const translations: Record<Language, Record<TranslationKey, string>> = {
    en: {
        'common.back': 'Back',
        'common.cancel': 'Cancel',
        'common.configure': 'Configure',
        'common.continue': 'Continue',
        'common.deleteForever': 'Delete Forever',
        'common.download': 'Download',
        'common.loading': 'Loading',
        'common.move': 'Move',
        'common.restore': 'Restore',
        'common.sync': 'Sync',
        'common.trash': 'Trash',
        'common.upload': 'Upload',
        'common.darkMode': 'Dark Mode',
        'common.language': 'Language',
        'common.checkingSession': 'Checking your Telegram session...',
        'common.signOut': 'Sign Out',
        'common.size': 'Size',
        'common.name': 'Name',
        'common.date': 'Date',
        'common.sort': 'Sort',
        'context.addFavorite': 'Add Favorite',
        'context.details': 'Details',
        'context.fileActions': 'File actions',
        'context.moveToTrash': 'Move to Trash',
        'context.open': 'Open',
        'context.play': 'Play',
        'context.removeFavorite': 'Remove Favorite',
        'context.viewPdf': 'View PDF',
        'auth.accountConnect': 'Connect account',
        'auth.apiCredentialsHelp': 'How do I get my API credentials?',
        'auth.apiIdNumber': 'API ID must be a number',
        'auth.apiIdNoSpaces': 'API ID and API Hash cannot contain spaces. Please remove any spaces.',
        'auth.backToCode': 'Back to Code Entry',
        'auth.backToConfig': 'Back to Configuration',
        'auth.changePhone': 'Change Phone Number',
        'auth.cloudPassword': 'Cloud Password',
        'auth.connectAccount': 'Connect account',
        'auth.connecting': 'Connecting...',
        'auth.copyCredentials': 'Copy Your Credentials',
        'auth.createApplication': 'Create a New Application',
        'auth.credentialsRequired': 'Both API ID and Hash are required.',
        'auth.description': 'Connect once, then browse folders, stream media, preview documents, and move files without sending data through third-party servers.',
        'auth.desktopRequired': 'Desktop App Required',
        'auth.desktopRequiredBody': 'You are viewing the internal development server in a browser. This application cannot function here because it requires access to the system backend.',
        'auth.desktopRequiredHint': 'Please open the Telegram Drive window in your OS taskbar/dock to continue.',
        'auth.devMode': 'Dev Mode',
        'auth.enterPassword': 'Enter your password',
        'auth.gettingStarted': 'Getting Started',
        'auth.goDeveloperPortal': "Go to Telegram's Developer Portal",
        'auth.headline': 'Your Telegram storage, managed like a native drive.',
        'auth.helpCreateApp': 'Click "API development tools" and create a new application. Use any name and description you like.',
        'auth.helpCredentials': 'After creating the app, copy your API ID and API Hash, then paste them into the previous screen.',
        'auth.helpPortal': 'Visit my.telegram.org and log in with your phone number.',
        'auth.localFirstCloud': 'Local first cloud',
        'auth.localKeys': 'Local keys',
        'auth.noRestart': 'Do not restart the app. The timer will reset if you do.',
        'auth.openTelegram': 'Open my.telegram.org',
        'auth.password2fa': 'Your account has Two-Factor Authentication enabled. Please enter your cloud password to continue.',
        'auth.phoneNumber': 'Phone Number',
        'auth.privacy': 'Privacy',
        'auth.privacyNote': 'Your credentials are stored locally on your device and are never sent to any third-party servers. All data goes directly between you and Telegram.',
        'auth.privateConsole': 'Private storage console',
        'auth.rangeReady': 'Range ready',
        'auth.signIn': 'Sign In',
        'auth.storage': 'Storage',
        'auth.streaming': 'Streaming',
        'auth.subtitle': 'Set up your Telegram API credentials and session.',
        'auth.telegramCode': 'Telegram Code',
        'auth.tooManyRequests': 'Too Many Requests',
        'auth.tooManyRequestsBody': 'Telegram has temporarily limited your actions. Please wait before trying again.',
        'auth.unknownError': 'Unknown error',
        'auth.unlock': 'Unlock',
        'auth.verifying': 'Verifying...',
        'auth.passwordFailed': 'Password verification failed.',
        'diagnostics.authActive': 'Authenticated session is active',
        'diagnostics.authInactive': 'Session is not connected',
        'diagnostics.generated': 'Generated',
        'diagnostics.healthCheck': 'Health Check',
        'diagnostics.refresh': 'Refresh',
        'diagnostics.running': 'Running diagnostics...',
        'diagnostics.telegramAuth': 'Telegram authorization',
        'diagnostics.title': 'Diagnostics',
        'details.addTag': 'Add tag',
        'details.created': 'Created',
        'details.fileDetails': 'File details',
        'details.folder': 'Folder',
        'details.inspector': 'Inspector',
        'details.messageId': 'Message ID',
        'details.noTags': 'No tags',
        'details.original': 'Original',
        'details.pin': 'Pin',
        'details.preview': 'Preview',
        'details.rename': 'Rename',
        'details.size': 'Size',
        'details.tags': 'Collections',
        'details.type': 'Type',
        'details.unpin': 'Unpin',
        'empty.collectionMessage': 'Add this tag from the file inspector.',
        'empty.collectionTitle': 'Collection is empty',
        'empty.defaultMessage': 'Drop files into this window or use the upload command to add items to the current folder.',
        'empty.defaultTitle': 'This folder is empty',
        'empty.dragDrop': 'Drag & drop',
        'empty.favoritesMessage': 'Pin important files to keep them one click away.',
        'empty.favoritesTitle': 'No favorites yet',
        'empty.mediaMessage': 'Audio and video files you open or tag will appear here.',
        'empty.mediaTitle': 'No media found',
        'empty.recentMessage': 'Preview, download, rename, or pin files and they will appear here.',
        'empty.recentTitle': 'No recent activity',
        'empty.tipSearch': 'Tip: Use Cmd + F to search',
        'empty.trashMessage': 'Files moved to Trash will appear here before permanent deletion.',
        'empty.trashTitle': 'Trash is empty',
        'empty.uploadFiles': 'Upload Files',
        'explorer.errorLoading': 'Error loading files',
        'explorer.loading': 'Loading your files...',
        'explorer.uploadFile': 'Upload File',
        'explorer.uploadFileDots': 'Upload File...',
        'filters.allTypes': 'All types',
        'filters.archives': 'Archives',
        'filters.audio': 'Audio',
        'filters.date': 'Date',
        'filters.documents': 'Documents',
        'filters.favorites': 'Favorites',
        'filters.images': 'Images',
        'filters.maxMb': 'Max MB',
        'filters.minMb': 'Min MB',
        'filters.other': 'Other',
        'filters.pdf': 'PDF',
        'filters.reset': 'Reset',
        'filters.result': 'result',
        'filters.results': 'results',
        'filters.tag': 'Tag',
        'filters.tagPlaceholder': 'Search tag...',
        'filters.today': 'Today',
        'filters.type': 'Type',
        'filters.videos': 'Videos',
        'filters.anyTime': 'Any time',
        'filters.thisMonth': 'This month',
        'filters.thisWeek': 'This week',
        'rename.fileTitle': 'Rename file',
        'rename.fileDescription': 'This changes the display name inside Telegram Drive.',
        'rename.folderTitle': 'Rename folder',
        'rename.folderDescription': 'This updates the Telegram Drive folder title.',
        'search.resultsFor': 'Search Results for',
        'sidebar.account': 'Telegram account',
        'sidebar.accountLoading': 'Loading account...',
        'sidebar.collections': 'Collections',
        'sidebar.connected': 'Connected to Telegram',
        'sidebar.createFolder': 'Create Folder',
        'sidebar.disconnected': 'Disconnected from Telegram',
        'sidebar.driveConsole': 'Drive Console',
        'sidebar.favorites': 'Favorites',
        'sidebar.tagManager': 'Tag Manager',
        'sidebar.backup': 'Metadata Backup',
        'sidebar.activity': 'Activity Log',
        'sidebar.analytics': 'Storage Analytics',
        'sidebar.folders': 'Folders',
        'sidebar.googleDrive': 'Google Drive',
        'sidebar.library': 'Library',
        'sidebar.localSync': 'Local Sync',
        'sidebar.logout': 'Logout',
        'sidebar.media': 'Media Library',
        'sidebar.recent': 'Recent',
        'sidebar.savedMessages': 'Saved Messages',
        'sidebar.syncing': 'Syncing...',
        'sidebar.tools': 'Tools',
        'sidebar.version': 'Version',
        'sidebar.author': 'Built by',
        'tags.manager': 'Tag Manager',
        'tags.title': 'Organize tags across files',
        'tags.description': 'Rename, delete, and open local tag collections without touching the Telegram files themselves.',
        'tags.tags': 'tags',
        'tags.searchPlaceholder': 'Search tags...',
        'tags.files': 'files',
        'tags.delete': 'Delete tag',
        'tags.empty': 'No tags found.',
        'tags.deleteTitle': 'Delete tag',
        'tags.deleteMessage': 'Remove this tag from every file',
        'tags.renamed': 'Tag renamed.',
        'tags.deleted': 'Tag deleted.',
        'backup.console': 'Metadata Backup',
        'backup.title': 'Back up local metadata to Telegram',
        'backup.description': 'Create a compact JSON backup of tags, favorites, local names, trash state, recent items, activity log, and folder references. The backup file is uploaded to the selected Telegram folder, so you can restore it later from that folder.',
        'backup.backupToHome': 'Back up to Saved Messages',
        'backup.backupTo': 'Back up to',
        'backup.running': 'Working...',
        'backup.create': 'Create backup',
        'backup.restoreSelected': 'Restore selected backup',
        'backup.restore': 'Restore',
        'backup.selectHint': 'Select a metadata backup file from the current folder, or restore one from the visible backup list.',
        'backup.visibleBackups': 'Backups in current folder',
        'backup.noVisibleBackups': 'No metadata backup files are visible in this folder.',
        'backup.created': 'Metadata backup uploaded to Telegram.',
        'backup.failed': 'Backup failed',
        'backup.restoreConfirmTitle': 'Restore metadata backup',
        'backup.restoreConfirmMessage': 'This will replace local tags, favorites, display names, trash state, recent items, and activity log with the backup content.',
        'backup.invalid': 'Invalid Telegram Drive metadata backup',
        'backup.restored': 'Metadata restored.',
        'backup.restoreFailed': 'Restore failed',
        'activity.console': 'Activity Log',
        'activity.title': 'Recent workspace activity',
        'activity.description': 'Track local organization changes, backups, restores, uploads, downloads, and sync runs.',
        'activity.today': 'today',
        'activity.clear': 'Clear log',
        'activity.searchPlaceholder': 'Search activity...',
        'activity.all': 'All',
        'activity.empty': 'No activity found.',
        'activity.clearConfirm': 'Clear the local activity log on this device?',
        'activity.filesChanged': 'files',
        'activity.action.upload': 'Uploads',
        'activity.action.download': 'Downloads',
        'activity.action.tag_add': 'Tags',
        'activity.action.backup': 'Backups',
        'activity.action.metadata_restore': 'Restores',
        'activity.action.google_drive': 'Google Drive',
        'activity.action.rename': 'Renames',
        'activity.action.trash': 'Trash',
        'activity.action.restore': 'Restore',
        'activity.label.upload': 'Uploaded file',
        'activity.label.download': 'Queued download',
        'activity.label.bulkDownload': 'Queued bulk download',
        'activity.label.folderDownload': 'Queued folder download',
        'activity.label.favoriteAdded': 'Pinned file',
        'activity.label.favoriteRemoved': 'Unpinned file',
        'activity.label.tagAdded': 'Added tag',
        'activity.label.tagRemoved': 'Removed tag',
        'activity.label.tagRenamed': 'Renamed tag',
        'activity.label.tagDeleted': 'Deleted tag',
        'activity.label.trash': 'Moved to Trash',
        'activity.label.restore': 'Restored file',
        'activity.label.rename': 'Renamed file',
        'activity.label.folderRename': 'Renamed folder',
        'activity.label.folderCreate': 'Created folder',
        'activity.label.move': 'Moved files',
        'activity.label.sync': 'Ran local sync',
        'activity.label.backup': 'Created metadata backup',
        'activity.label.metadataRestore': 'Restored metadata backup',
        'activity.label.googleDriveConnect': 'Connected Google Drive',
        'activity.label.googleDriveDisconnect': 'Disconnected Google Drive',
        'activity.label.googleDriveFolder': 'Prepared Google Drive folder',
        'activity.label.googleDriveBackup': 'Backed up to Google Drive',
        'activity.label.deleteForever': 'Deleted permanently',
        'gdrive.console': 'Google Drive Backup',
        'gdrive.title': 'Back up Telegram files to Google Drive',
        'gdrive.description': 'Connect your own Google OAuth desktop client, create a Drive folder, and upload selected Telegram files to Google Drive as a first one-way backup workflow.',
        'gdrive.connection': 'Google connection',
        'gdrive.clientId': 'OAuth Client ID',
        'gdrive.clientIdPlaceholder': 'Paste your Google OAuth desktop client ID...',
        'gdrive.connect': 'Connect Google',
        'gdrive.reconnect': 'Reconnect',
        'gdrive.disconnect': 'Disconnect',
        'gdrive.disconnectConfirm': 'Remove the saved Google Drive token from this device?',
        'gdrive.connected': 'Google Drive connected',
        'gdrive.connectHint': 'Create an OAuth Desktop Client in Google Cloud, paste the Client ID here, then connect.',
        'gdrive.connectRequired': 'Connect Google Drive first',
        'gdrive.connectFailed': 'Google Drive connection failed',
        'gdrive.targetFolder': 'Backup destination',
        'gdrive.folderName': 'Drive folder name',
        'gdrive.createFolder': 'Create or find folder',
        'gdrive.folderReady': 'Folder ready',
        'gdrive.folderId': 'Folder ID',
        'gdrive.folderFailed': 'Folder setup failed',
        'gdrive.backupFile': 'Back up one file',
        'gdrive.backupFileHint': 'This first version uploads one Telegram file from the current folder to Google Drive.',
        'gdrive.backup': 'Back up to Drive',
        'gdrive.backupDone': 'File backed up to Google Drive.',
        'gdrive.backupFailed': 'Google Drive backup failed',
        'gdrive.noFiles': 'No files in the current Telegram folder.',
        'gdrive.openInDrive': 'Open in Drive',
        'gdrive.setupNote': 'Setup note: use a Google Cloud OAuth client of type Desktop app. The app uses a local loopback callback and requests Drive file access only for files it creates or opens.',
        'gdrive.setupTitle': 'Google OAuth setup guide',
        'gdrive.setupStep1': 'Open Google Cloud Console and create or select a project.',
        'gdrive.setupStep2': 'Enable Google Drive API for that project.',
        'gdrive.setupStep3': 'Configure the OAuth consent screen for your Google account.',
        'gdrive.setupStep4': 'Open Credentials and create an OAuth Client ID.',
        'gdrive.setupStep5': 'Choose Desktop app as the application type.',
        'gdrive.setupStep6': 'Copy the Client ID and paste it into the field above.',
        'gdrive.link.cloudConsole': 'Google Cloud Console',
        'gdrive.link.driveApi': 'Enable Drive API',
        'gdrive.link.consent': 'OAuth consent',
        'gdrive.link.credentials': 'Credentials',
        'analytics.console': 'Storage Analytics',
        'analytics.title': 'Known storage overview',
        'analytics.description': 'Analyze files Telegram Drive has seen locally: current folder files plus locally indexed tagged, favorite, renamed, and recent files.',
        'analytics.totalSize': 'Known size',
        'analytics.knownFiles': 'Known files',
        'analytics.taggedFiles': 'Tag links',
        'analytics.byType': 'By file type',
        'analytics.byFolder': 'By folder',
        'analytics.files': 'files',
        'analytics.empty': 'No files to analyze yet.',
        'analytics.largestFiles': 'Largest files',
        'analytics.topTags': 'Top tags by size',
        'analytics.noTags': 'No tagged files yet.',
        'analytics.favorites': 'Favorites',
        'analytics.tags': 'Tags',
        'analytics.category.image': 'Images',
        'analytics.category.video': 'Videos',
        'analytics.category.audio': 'Audio',
        'analytics.category.pdf': 'PDF',
        'analytics.category.document': 'Documents',
        'analytics.category.archive': 'Archives',
        'analytics.category.other': 'Other',
        'sync.automation': 'Automation',
        'sync.chooseFolder': 'Choose local folder',
        'sync.disabled': 'Disabled',
        'sync.enabled': 'Enabled',
        'sync.interval': 'Interval',
        'sync.lastRun': 'Last run',
        'sync.notRun': 'Not run yet',
        'sync.reset': 'Reset',
        'sync.status': 'Status',
        'sync.syncNow': 'Sync Now',
        'sync.syncing': 'Syncing',
        'sync.title': 'Local Sync',
        'sync.minutes': 'min',
        'topbar.advancedSearch': 'Advanced Search',
        'topbar.darkMode': 'Dark Mode',
        'topbar.downloadAllFiles': 'Download All Files',
        'topbar.downloadFolder': 'Download Folder',
        'topbar.filters': 'Filters',
        'topbar.lightMode': 'Light Mode',
        'topbar.search': 'Search files...',
        'topbar.selected': 'selected',
        'topbar.switchGrid': 'Switch to Grid',
        'topbar.switchList': 'Switch to List',
        'topbar.telegramCloud': 'Telegram cloud',
        'topbar.toggleLayout': 'Toggle Layout',
        'topbar.uploadFiles': 'Upload Files',
        'topbar.workspace': 'Workspace',
    },
    vi: {
        'common.back': 'Quay lại',
        'common.cancel': 'Hủy',
        'common.configure': 'Cấu hình',
        'common.continue': 'Tiếp tục',
        'common.deleteForever': 'Xóa vĩnh viễn',
        'common.download': 'Tải xuống',
        'common.loading': 'Đang tải',
        'common.move': 'Di chuyển',
        'common.restore': 'Khôi phục',
        'common.sync': 'Đồng bộ',
        'common.trash': 'Thùng rác',
        'common.upload': 'Tải lên',
        'common.darkMode': 'Giao diện tối',
        'common.language': 'Ngôn ngữ',
        'common.checkingSession': 'Đang kiểm tra phiên Telegram...',
        'common.signOut': 'Đăng xuất',
        'common.size': 'Dung lượng',
        'common.name': 'Tên',
        'common.date': 'Ngày',
        'common.sort': 'Sắp xếp',
        'context.addFavorite': 'Thêm yêu thích',
        'context.details': 'Chi tiết',
        'context.fileActions': 'Thao tác file',
        'context.moveToTrash': 'Đưa vào thùng rác',
        'context.open': 'Mở',
        'context.play': 'Phát',
        'context.removeFavorite': 'Bỏ yêu thích',
        'context.viewPdf': 'Xem PDF',
        'auth.accountConnect': 'Kết nối tài khoản',
        'auth.apiCredentialsHelp': 'Lấy API ID/API Hash ở đâu?',
        'auth.apiIdNumber': 'API ID phải là số',
        'auth.apiIdNoSpaces': 'API ID và API Hash không được chứa khoảng trắng. Vui lòng xóa khoảng trắng.',
        'auth.backToCode': 'Quay lại nhập mã',
        'auth.backToConfig': 'Quay lại cấu hình',
        'auth.changePhone': 'Đổi số điện thoại',
        'auth.cloudPassword': 'Mật khẩu cloud',
        'auth.connectAccount': 'Kết nối tài khoản',
        'auth.connecting': 'Đang kết nối...',
        'auth.copyCredentials': 'Sao chép thông tin API',
        'auth.createApplication': 'Tạo ứng dụng mới',
        'auth.credentialsRequired': 'Cần nhập cả API ID và API Hash.',
        'auth.description': 'Kết nối một lần, sau đó duyệt thư mục, stream media, xem trước tài liệu và di chuyển file mà không gửi dữ liệu qua máy chủ bên thứ ba.',
        'auth.desktopRequired': 'Cần mở app desktop',
        'auth.desktopRequiredBody': 'Bạn đang xem dev server trong trình duyệt. Ứng dụng cần backend hệ thống nên không thể chạy đầy đủ ở đây.',
        'auth.desktopRequiredHint': 'Hãy mở cửa sổ Telegram Drive trong Dock/taskbar để tiếp tục.',
        'auth.devMode': 'Chế độ dev',
        'auth.enterPassword': 'Nhập mật khẩu',
        'auth.gettingStarted': 'Bắt đầu',
        'auth.goDeveloperPortal': 'Vào cổng developer của Telegram',
        'auth.headline': 'Quản lý lưu trữ Telegram như một ổ đĩa native.',
        'auth.helpCreateApp': 'Bấm "API development tools" và tạo một ứng dụng mới. Bạn có thể dùng tên và mô tả tùy ý.',
        'auth.helpCredentials': 'Sau khi tạo app, sao chép API ID và API Hash rồi dán vào màn hình trước.',
        'auth.helpPortal': 'Truy cập my.telegram.org và đăng nhập bằng số điện thoại.',
        'auth.localFirstCloud': 'Cloud ưu tiên local',
        'auth.localKeys': 'Khóa local',
        'auth.noRestart': 'Không khởi động lại app. Bộ đếm sẽ bị đặt lại nếu bạn làm vậy.',
        'auth.openTelegram': 'Mở my.telegram.org',
        'auth.password2fa': 'Tài khoản của bạn đang bật xác thực hai lớp. Nhập mật khẩu cloud để tiếp tục.',
        'auth.phoneNumber': 'Số điện thoại',
        'auth.privacy': 'Riêng tư',
        'auth.privacyNote': 'Thông tin API được lưu cục bộ trên thiết bị của bạn và không gửi tới máy chủ bên thứ ba. Dữ liệu đi trực tiếp giữa bạn và Telegram.',
        'auth.privateConsole': 'Bảng điều khiển lưu trữ riêng tư',
        'auth.rangeReady': 'Hỗ trợ tua',
        'auth.signIn': 'Đăng nhập',
        'auth.storage': 'Lưu trữ',
        'auth.streaming': 'Stream',
        'auth.subtitle': 'Thiết lập API Telegram và phiên đăng nhập.',
        'auth.telegramCode': 'Mã Telegram',
        'auth.tooManyRequests': 'Quá nhiều yêu cầu',
        'auth.tooManyRequestsBody': 'Telegram đang tạm giới hạn thao tác của bạn. Vui lòng đợi rồi thử lại.',
        'auth.unknownError': 'Lỗi không xác định',
        'auth.unlock': 'Mở khóa',
        'auth.verifying': 'Đang xác minh...',
        'auth.passwordFailed': 'Xác minh mật khẩu thất bại.',
        'diagnostics.authActive': 'Phiên đăng nhập đang hoạt động',
        'diagnostics.authInactive': 'Phiên chưa kết nối',
        'diagnostics.generated': 'Tạo lúc',
        'diagnostics.healthCheck': 'Kiểm tra sức khỏe',
        'diagnostics.refresh': 'Làm mới',
        'diagnostics.running': 'Đang kiểm tra...',
        'diagnostics.telegramAuth': 'Ủy quyền Telegram',
        'diagnostics.title': 'Chẩn đoán',
        'details.addTag': 'Thêm tag',
        'details.created': 'Ngày tạo',
        'details.fileDetails': 'Chi tiết file',
        'details.folder': 'Thư mục',
        'details.inspector': 'Thông tin',
        'details.messageId': 'Message ID',
        'details.noTags': 'Chưa có tag',
        'details.original': 'Tên gốc',
        'details.pin': 'Ghim',
        'details.preview': 'Xem trước',
        'details.rename': 'Đổi tên',
        'details.size': 'Dung lượng',
        'details.tags': 'Bộ sưu tập',
        'details.type': 'Loại',
        'details.unpin': 'Bỏ ghim',
        'empty.collectionMessage': 'Thêm tag này từ bảng thông tin file.',
        'empty.collectionTitle': 'Bộ sưu tập đang trống',
        'empty.defaultMessage': 'Kéo file vào cửa sổ này hoặc dùng nút tải lên để thêm vào thư mục hiện tại.',
        'empty.defaultTitle': 'Thư mục này đang trống',
        'empty.dragDrop': 'Kéo thả',
        'empty.favoritesMessage': 'Ghim file quan trọng để truy cập nhanh.',
        'empty.favoritesTitle': 'Chưa có file yêu thích',
        'empty.mediaMessage': 'File âm thanh và video bạn mở hoặc gắn tag sẽ xuất hiện ở đây.',
        'empty.mediaTitle': 'Chưa có media',
        'empty.recentMessage': 'File đã xem trước, tải xuống, đổi tên hoặc ghim sẽ xuất hiện ở đây.',
        'empty.recentTitle': 'Chưa có hoạt động gần đây',
        'empty.tipSearch': 'Mẹo: dùng Cmd + F để tìm kiếm',
        'empty.trashMessage': 'File đưa vào thùng rác sẽ xuất hiện ở đây trước khi xóa vĩnh viễn.',
        'empty.trashTitle': 'Thùng rác đang trống',
        'empty.uploadFiles': 'Tải file lên',
        'explorer.errorLoading': 'Không tải được file',
        'explorer.loading': 'Đang tải file...',
        'explorer.uploadFile': 'Tải file lên',
        'explorer.uploadFileDots': 'Tải file lên...',
        'filters.allTypes': 'Tất cả loại file',
        'filters.archives': 'File nén',
        'filters.audio': 'Âm thanh',
        'filters.date': 'Ngày',
        'filters.documents': 'Tài liệu',
        'filters.favorites': 'Yêu thích',
        'filters.images': 'Hình ảnh',
        'filters.maxMb': 'Tối đa MB',
        'filters.minMb': 'Tối thiểu MB',
        'filters.other': 'Khác',
        'filters.pdf': 'PDF',
        'filters.reset': 'Đặt lại',
        'filters.result': 'kết quả',
        'filters.results': 'kết quả',
        'filters.tag': 'Tag',
        'filters.tagPlaceholder': 'Tìm tag...',
        'filters.today': 'Hôm nay',
        'filters.type': 'Loại',
        'filters.videos': 'Video',
        'filters.anyTime': 'Mọi thời điểm',
        'filters.thisMonth': 'Tháng này',
        'filters.thisWeek': 'Tuần này',
        'rename.fileTitle': 'Đổi tên file',
        'rename.fileDescription': 'Thay đổi tên hiển thị trong Telegram Drive.',
        'rename.folderTitle': 'Đổi tên thư mục',
        'rename.folderDescription': 'Cập nhật tiêu đề thư mục Telegram Drive.',
        'search.resultsFor': 'Kết quả tìm kiếm cho',
        'sidebar.account': 'Tài khoản Telegram',
        'sidebar.accountLoading': 'Đang tải tài khoản...',
        'sidebar.collections': 'Bộ sưu tập',
        'sidebar.connected': 'Đã kết nối Telegram',
        'sidebar.createFolder': 'Tạo thư mục',
        'sidebar.disconnected': 'Mất kết nối Telegram',
        'sidebar.driveConsole': 'Bảng điều khiển',
        'sidebar.favorites': 'Yêu thích',
        'sidebar.tagManager': 'Quản lý tag',
        'sidebar.backup': 'Backup metadata',
        'sidebar.activity': 'Nhật ký hoạt động',
        'sidebar.analytics': 'Phân tích lưu trữ',
        'sidebar.folders': 'Thư mục',
        'sidebar.googleDrive': 'Google Drive',
        'sidebar.library': 'Thư viện',
        'sidebar.localSync': 'Đồng bộ local',
        'sidebar.logout': 'Đăng xuất',
        'sidebar.media': 'Thư viện media',
        'sidebar.recent': 'Gần đây',
        'sidebar.savedMessages': 'Tin nhắn đã lưu',
        'sidebar.syncing': 'Đang đồng bộ...',
        'sidebar.tools': 'Công cụ',
        'sidebar.version': 'Phiên bản',
        'sidebar.author': 'Thực hiện bởi',
        'tags.manager': 'Quản lý tag',
        'tags.title': 'Sắp xếp tag trên toàn bộ file',
        'tags.description': 'Đổi tên, xóa và mở bộ sưu tập tag local mà không thay đổi file gốc trên Telegram.',
        'tags.tags': 'tag',
        'tags.searchPlaceholder': 'Tìm tag...',
        'tags.files': 'file',
        'tags.delete': 'Xóa tag',
        'tags.empty': 'Không tìm thấy tag.',
        'tags.deleteTitle': 'Xóa tag',
        'tags.deleteMessage': 'Gỡ tag này khỏi tất cả file',
        'tags.renamed': 'Đã đổi tên tag.',
        'tags.deleted': 'Đã xóa tag.',
        'backup.console': 'Backup metadata',
        'backup.title': 'Backup metadata local lên Telegram',
        'backup.description': 'Tạo file JSON nhỏ chứa tag, yêu thích, tên hiển thị, trạng thái thùng rác, mục gần đây, nhật ký hoạt động và tham chiếu thư mục. File backup được upload vào thư mục Telegram bạn chọn để sau này mở đúng thư mục đó và restore lại.',
        'backup.backupToHome': 'Backup vào Tin nhắn đã lưu',
        'backup.backupTo': 'Backup vào',
        'backup.running': 'Đang chạy...',
        'backup.create': 'Tạo backup',
        'backup.restoreSelected': 'Restore file backup đã chọn',
        'backup.restore': 'Restore',
        'backup.selectHint': 'Chọn file metadata backup trong thư mục hiện tại, hoặc restore từ danh sách backup đang thấy.',
        'backup.visibleBackups': 'Backup trong thư mục hiện tại',
        'backup.noVisibleBackups': 'Không thấy file metadata backup nào trong thư mục này.',
        'backup.created': 'Đã upload metadata backup lên Telegram.',
        'backup.failed': 'Backup thất bại',
        'backup.restoreConfirmTitle': 'Restore metadata backup',
        'backup.restoreConfirmMessage': 'Thao tác này sẽ thay local tags, yêu thích, tên hiển thị, thùng rác, mục gần đây và nhật ký hoạt động bằng dữ liệu trong backup.',
        'backup.invalid': 'File backup metadata Telegram Drive không hợp lệ',
        'backup.restored': 'Đã restore metadata.',
        'backup.restoreFailed': 'Restore thất bại',
        'activity.console': 'Nhật ký hoạt động',
        'activity.title': 'Hoạt động gần đây',
        'activity.description': 'Theo dõi thay đổi sắp xếp local, backup, restore, upload, download và đồng bộ.',
        'activity.today': 'hôm nay',
        'activity.clear': 'Xóa nhật ký',
        'activity.searchPlaceholder': 'Tìm hoạt động...',
        'activity.all': 'Tất cả',
        'activity.empty': 'Không có hoạt động phù hợp.',
        'activity.clearConfirm': 'Xóa nhật ký hoạt động local trên thiết bị này?',
        'activity.filesChanged': 'file',
        'activity.action.upload': 'Upload',
        'activity.action.download': 'Download',
        'activity.action.tag_add': 'Tag',
        'activity.action.backup': 'Backup',
        'activity.action.metadata_restore': 'Restore',
        'activity.action.google_drive': 'Google Drive',
        'activity.action.rename': 'Đổi tên',
        'activity.action.trash': 'Thùng rác',
        'activity.action.restore': 'Khôi phục',
        'activity.label.upload': 'Đã upload file',
        'activity.label.download': 'Đã đưa vào hàng đợi tải xuống',
        'activity.label.bulkDownload': 'Đã đưa nhiều file vào hàng đợi tải xuống',
        'activity.label.folderDownload': 'Đã đưa thư mục vào hàng đợi tải xuống',
        'activity.label.favoriteAdded': 'Đã ghim file',
        'activity.label.favoriteRemoved': 'Đã bỏ ghim file',
        'activity.label.tagAdded': 'Đã thêm tag',
        'activity.label.tagRemoved': 'Đã gỡ tag',
        'activity.label.tagRenamed': 'Đã đổi tên tag',
        'activity.label.tagDeleted': 'Đã xóa tag',
        'activity.label.trash': 'Đã đưa vào thùng rác',
        'activity.label.restore': 'Đã khôi phục file',
        'activity.label.rename': 'Đã đổi tên file',
        'activity.label.folderRename': 'Đã đổi tên thư mục',
        'activity.label.folderCreate': 'Đã tạo thư mục',
        'activity.label.move': 'Đã di chuyển file',
        'activity.label.sync': 'Đã chạy đồng bộ local',
        'activity.label.backup': 'Đã tạo metadata backup',
        'activity.label.metadataRestore': 'Đã restore metadata backup',
        'activity.label.googleDriveConnect': 'Đã kết nối Google Drive',
        'activity.label.googleDriveDisconnect': 'Đã ngắt Google Drive',
        'activity.label.googleDriveFolder': 'Đã chuẩn bị thư mục Google Drive',
        'activity.label.googleDriveBackup': 'Đã backup lên Google Drive',
        'activity.label.deleteForever': 'Đã xóa vĩnh viễn',
        'gdrive.console': 'Backup Google Drive',
        'gdrive.title': 'Backup file Telegram sang Google Drive',
        'gdrive.description': 'Kết nối OAuth Desktop Client của Google, tạo thư mục Drive và upload file Telegram đã chọn sang Google Drive. Đây là bản backup một chiều đầu tiên.',
        'gdrive.connection': 'Kết nối Google',
        'gdrive.clientId': 'OAuth Client ID',
        'gdrive.clientIdPlaceholder': 'Dán Google OAuth desktop client ID...',
        'gdrive.connect': 'Kết nối Google',
        'gdrive.reconnect': 'Kết nối lại',
        'gdrive.disconnect': 'Ngắt kết nối',
        'gdrive.disconnectConfirm': 'Xóa token Google Drive đã lưu trên thiết bị này?',
        'gdrive.connected': 'Đã kết nối Google Drive',
        'gdrive.connectHint': 'Tạo OAuth Desktop Client trong Google Cloud, dán Client ID vào đây rồi kết nối.',
        'gdrive.connectRequired': 'Cần kết nối Google Drive trước',
        'gdrive.connectFailed': 'Kết nối Google Drive thất bại',
        'gdrive.targetFolder': 'Nơi backup',
        'gdrive.folderName': 'Tên thư mục Drive',
        'gdrive.createFolder': 'Tạo hoặc tìm thư mục',
        'gdrive.folderReady': 'Thư mục sẵn sàng',
        'gdrive.folderId': 'Folder ID',
        'gdrive.folderFailed': 'Thiết lập thư mục thất bại',
        'gdrive.backupFile': 'Backup một file',
        'gdrive.backupFileHint': 'Bản đầu tiên này upload một file Telegram trong thư mục hiện tại sang Google Drive.',
        'gdrive.backup': 'Backup lên Drive',
        'gdrive.backupDone': 'Đã backup file lên Google Drive.',
        'gdrive.backupFailed': 'Backup Google Drive thất bại',
        'gdrive.noFiles': 'Thư mục Telegram hiện tại chưa có file.',
        'gdrive.openInDrive': 'Mở trong Drive',
        'gdrive.setupNote': 'Ghi chú thiết lập: dùng Google Cloud OAuth client loại Desktop app. App dùng callback local và chỉ xin quyền Drive file cho các file do app tạo hoặc mở.',
        'gdrive.setupTitle': 'Hướng dẫn setup Google OAuth',
        'gdrive.setupStep1': 'Mở Google Cloud Console và tạo hoặc chọn một project.',
        'gdrive.setupStep2': 'Bật Google Drive API cho project đó.',
        'gdrive.setupStep3': 'Cấu hình OAuth consent screen cho tài khoản Google của bạn.',
        'gdrive.setupStep4': 'Mở Credentials và tạo OAuth Client ID.',
        'gdrive.setupStep5': 'Chọn loại ứng dụng Desktop app.',
        'gdrive.setupStep6': 'Copy Client ID và dán vào ô phía trên.',
        'gdrive.link.cloudConsole': 'Google Cloud Console',
        'gdrive.link.driveApi': 'Bật Drive API',
        'gdrive.link.consent': 'OAuth consent',
        'gdrive.link.credentials': 'Credentials',
        'analytics.console': 'Phân tích lưu trữ',
        'analytics.title': 'Tổng quan file đã biết',
        'analytics.description': 'Phân tích các file Telegram Drive đã thấy local: file trong thư mục hiện tại và các file đã được index qua tag, yêu thích, đổi tên hoặc gần đây.',
        'analytics.totalSize': 'Dung lượng đã biết',
        'analytics.knownFiles': 'File đã biết',
        'analytics.taggedFiles': 'Liên kết tag',
        'analytics.byType': 'Theo loại file',
        'analytics.byFolder': 'Theo thư mục',
        'analytics.files': 'file',
        'analytics.empty': 'Chưa có file để phân tích.',
        'analytics.largestFiles': 'File lớn nhất',
        'analytics.topTags': 'Tag lớn nhất theo dung lượng',
        'analytics.noTags': 'Chưa có file được gắn tag.',
        'analytics.favorites': 'Yêu thích',
        'analytics.tags': 'Tag',
        'analytics.category.image': 'Hình ảnh',
        'analytics.category.video': 'Video',
        'analytics.category.audio': 'Âm thanh',
        'analytics.category.pdf': 'PDF',
        'analytics.category.document': 'Tài liệu',
        'analytics.category.archive': 'File nén',
        'analytics.category.other': 'Khác',
        'sync.automation': 'Tự động hóa',
        'sync.chooseFolder': 'Chọn thư mục local',
        'sync.disabled': 'Đang tắt',
        'sync.enabled': 'Đang bật',
        'sync.interval': 'Chu kỳ',
        'sync.lastRun': 'Lần chạy cuối',
        'sync.notRun': 'Chưa chạy',
        'sync.reset': 'Đặt lại',
        'sync.status': 'Trạng thái',
        'sync.syncNow': 'Đồng bộ ngay',
        'sync.syncing': 'Đang đồng bộ',
        'sync.title': 'Đồng bộ local',
        'sync.minutes': 'phút',
        'topbar.advancedSearch': 'Tìm kiếm nâng cao',
        'topbar.darkMode': 'Giao diện tối',
        'topbar.downloadAllFiles': 'Tải tất cả file',
        'topbar.downloadFolder': 'Tải thư mục',
        'topbar.filters': 'Bộ lọc',
        'topbar.lightMode': 'Giao diện sáng',
        'topbar.search': 'Tìm file...',
        'topbar.selected': 'đã chọn',
        'topbar.switchGrid': 'Chuyển dạng lưới',
        'topbar.switchList': 'Chuyển dạng danh sách',
        'topbar.telegramCloud': 'Telegram cloud',
        'topbar.toggleLayout': 'Đổi bố cục',
        'topbar.uploadFiles': 'Tải file lên',
        'topbar.workspace': 'Không gian làm việc',
    },
};

interface LanguageContextType {
    language: Language;
    setLanguage: (language: Language) => void;
    toggleLanguage: () => void;
    t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

function getInitialLanguage(): Language {
    if (typeof window !== 'undefined') {
        const saved = localStorage.getItem('language');
        if (saved === 'en' || saved === 'vi') return saved;
        if (navigator.language.toLowerCase().startsWith('vi')) return 'vi';
    }
    return 'en';
}

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>(getInitialLanguage);

    const setLanguage = (nextLanguage: Language) => {
        localStorage.setItem('language', nextLanguage);
        setLanguageState(nextLanguage);
    };

    const value = useMemo<LanguageContextType>(() => ({
        language,
        setLanguage,
        toggleLanguage: () => setLanguage(language === 'en' ? 'vi' : 'en'),
        t: (key) => translations[language][key] || translations.en[key] || key,
    }), [language]);

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
    return context;
}
